base-url:    /

pygments:    false
markdown:    maruku
permalink:   date

site-title:             Stephan Smith
bio-fullname:           Stephan Smith
bio-nickname:           slsmith
bio-email-address:      stephan@getbooks.ws
bio-phone-number:       +1 757 822 3574

google-web-property-id: UA-735021-17
disqus-username:        NA
twitter-username:       NA
linkedin-username:      NA
drupal-username:        NA
github-username:        slsmith
feedburner-username:    d1b1
delicious-username:     NA

enabled-delicious:      true
